--Creation of part table
CREATE TABLE IF NOT EXISTS PART (
  P_PARTKEY INT NOT NULL,
  P_NAME varchar(55) NOT NULL,
  P_MFGR char(55) NOT NULL,
  P_BRAND char(10) NOT NULL,
  P_TYPE varchar(35) NOT NULL,
  P_SIZE INT NOT NULL,
  P_CONTAINER char(10),
  P_RETAILPRICE float NOT NULL,
  P_COMMENT varchar(117),
  PRIMARY KEY (P_PARTKEY)
);

--Creation of region table
  CREATE TABLE IF NOT EXISTS REGION (
  R_REGIONKEY INT NOT NULL,
  R_NAME char(25) NOT NULL,
  R_COMMENT varchar(152), 
  PRIMARY KEY (R_REGIONKEY)
);

--Creation of nation table
CREATE TABLE IF NOT EXISTS NATION (
  N_NATIONKEY INT NOT NULL,
  N_NAME char(25) NOT NULL,
  N_REGIONKEY INT NOT NULL,
  N_COMMENT varchar(152),
  PRIMARY KEY (N_NATIONKEY),
  CONSTRAINT fk_region
    FOREIGN KEY (N_REGIONKEY)
      REFERENCES region(R_REGIONKEY)
);

--Creation of supplier table
CREATE TABLE IF NOT EXISTS SUPPLIER (
  S_SUPPKEY INT NOT NULL,
  S_NAME char(15) NOT NULL,
  S_ADDRESS varchar(40) NOT NULL,
  S_NATIONKEY INT NOT NULL,
  S_PHONE char(15) NOT NULL,
  S_ACCTBAL float NOT NULL,
  S_COMMENT varchar(101),
  PRIMARY KEY (S_SUPPKEY),
  CONSTRAINT fk_nation
    FOREIGN KEY (S_NATIONKEY)
      REFERENCES nation(N_NATIONKEY)
);

--Creation of partsupp table
CREATE TABLE IF NOT EXISTS PARTSUPP (
  PS_PARTKEY INT NOT NULL,
  PS_SUPPKEY INT NOT NULL,
  PS_AVAILQTY INT NOT NULL,
  PS_SUPPLYCOST float NOT NULL,
  PS_COMMENT varchar(199),
  PRIMARY KEY (PS_PARTKEY,PS_SUPPKEY),
  CONSTRAINT fk_part
    FOREIGN KEY (PS_PARTKEY)
      REFERENCES part(P_PARTKEY),
  CONSTRAINT fk_supplier
    FOREIGN KEY (PS_SUPPKEY)
      REFERENCES supplier(S_SUPPKEY)
);

--Creation of customer table
CREATE TABLE IF NOT EXISTS CUSTOMER (
  C_CUSTKEY INT NOT NULL,
  C_NAME varchar(35) NOT NULL,
  C_ADDRESS varchar(40) NOT NULL,
  C_NATIONKEY INT NOT NULL,
  C_PHONE char(15) NOT NULL,
  C_ACCTBAL float NOT NULL,
  C_MKTSEGMENT char(10) NOT NULL,
  C_COMMENT varchar(117),
  PRIMARY KEY (C_CUSTKEY),
  CONSTRAINT fk_nation
    FOREIGN KEY (C_NATIONKEY)
      REFERENCES nation(N_NATIONKEY)
);

--Creation of orders table
CREATE TABLE IF NOT EXISTS ORDERS (
  O_ORDERKEY INT NOT NULL,
  O_CUSTKEY INT NOT NULL,
  O_ORDERSTATUS char(1)NOT NULL,
  O_TOTALPRICE float NOT NULL,
  O_ORDERDATE date NOT NULL,
  O_ORDERPRIORITY char(15) NOT NULL,
  O_CLERK char(15) NOT NULL,
  O_SHIPPRIORITY INT NOT NULL,
  O_COMMENT varchar(79),
  PRIMARY KEY (O_ORDERKEY),
  CONSTRAINT fk_customer
    FOREIGN KEY (O_CUSTKEY)
      REFERENCES customer(C_CUSTKEY)
);

--Creation of lineitem table
CREATE TABLE IF NOT EXISTS LINEITEM (
  L_ORDERKEY INT NOT NULL,
  L_PARTKEY INT NOT NULL,
  L_SUPPKEY INT NOT NULL,
  L_LINENUMBER INT NOT NULL,
  L_QUANTITY float NOT NULL,
  L_EXTENDEDPRICE float NOT NULL,
  L_DISCOUNT float NOT NULL,
  L_TAX float NOT NULL,
  L_RETURNFLAG char(1) NOT NULL,
  L_LINESTATUS char(1) NOT NULL,
  L_SHIPDATE date NOT NULL,
  L_COMMITDATE date NOT NULL,
  L_RECEIPTDATE date NOT NULL,
  L_SHIPINSTRUCT char(25) NOT NULL,
  L_SHIPMODE char(15) NOT NULL,
  L_COMMENT varchar(45),
  PRIMARY KEY (L_ORDERKEY, L_LINENUMBER),
  CONSTRAINT fk_part 
    FOREIGN KEY (L_PARTKEY)
      REFERENCES part(P_PARTKEY),
  CONSTRAINT fk_order
    FOREIGN KEY (L_ORDERKEY)
      REFERENCES orders(O_ORDERKEY),
  CONSTRAINT fk_supplier 
    FOREIGN KEY (L_SUPPKEY)
      REFERENCES supplier(S_SUPPKEY)
);